<a href="https://colab.research.google.com/github/Brke26/Artifical-neural-network-for-regression/blob/main/Artificial_Neural_Network_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.18.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
X = dataset.iloc[ : , 0:-1].values
y = dataset.iloc[ : , -1].values
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train , y_test = train_test_split(X,y , test_size= 0.2, random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [5]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [6]:
ann.add(tf.keras.layers.Dense(units = 6, activation="relu"))

### Adding the second hidden layer

In [7]:
ann.add(tf.keras.layers.Dense(units = 6, activation="relu"))

### Adding the output layer

In [8]:
ann.add(tf.keras.layers.Dense(units = 1)) #for regressions ann works better without activation function in the output layer

## Part 3 - Training the ANN

### Compiling the ANN

In [9]:
ann.compile(optimizer="adam",loss = "mean_squared_error")

### Training the ANN model on the Training set

In [10]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 183319.3906  
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 738.6205  
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 474.5193
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 416.4171
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 386.9706
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 350.1057  
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 316.9218  
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 297.3007  
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 266.4412
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 261.8932  
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 229.4997
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 216.4127  
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 195.5979  
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 169.9

### Predicting the results of the Test set

In [11]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
[[432.99 431.23]
 [464.13 460.01]
 [467.67 461.14]
 ...
 [474.88 473.26]
 [441.6  438.  ]
 [460.85 463.28]]
